name: 'Terraform CI'

on:
  pull_request:
    paths:
      - 'environments/**'
      - 'root/**'

jobs:
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  # Event `pull_request`: Compare the last commit of the main branch or last remote commit of the PR branch -> to the current commit of a PR branch.
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-directories
    steps:
      - uses: actions/checkout@v4
      - name: Run changed-files with dir_names
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v45
        with:
          dir_names: "true"

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files-dir-names.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done